services:
  redis:
    container_name: con-redis-pinterest
    image: redis:latest
    ports:
      - 6380:6379

  mysql:
    container_name: con-mysql-pinterest
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  pinterest:
    container_name: con-backend
    image: luquocphap/img-pinterest:latest
    ports:
      - 3070:3069
    env_file:
      - .env
  